name: Get twitter's trends with node.js script

on:
  schedule:
    - cron: "00 8,18 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout this repo
        uses: actions/checkout@v2
        
      - name: setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          
      - name: install packages
        run: npm install
        
      - name: Run script itself
        run: npm start
        env:
          UKRAINE_WOEID: "23424976"
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "update data" -a

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
